# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'no.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_no(object):
    def setupUi(self, no):
        no.setObjectName("no")
        no.resize(324, 248)
        self.label_2 = QtWidgets.QLabel(no)
        self.label_2.setGeometry(QtCore.QRect(80, 60, 171, 101))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_2.setFont(font)
        self.label_2.setWordWrap(True)
        self.label_2.setObjectName("label_2")

        self.retranslateUi(no)
        QtCore.QMetaObject.connectSlotsByName(no)

    def retranslateUi(self, no):
        _translate = QtCore.QCoreApplication.translate
        no.setWindowTitle(_translate("no", "Frame"))
        self.label_2.setText(_translate("no", "Данный пользователь отсутствует в системе!"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    no = QtWidgets.QFrame()
    ui = Ui_no()
    ui.setupUi(no)
    no.show()
    sys.exit(app.exec_())
