# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'order.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_order_form(object):
    def setupUi(self, order_form):
        order_form.setObjectName("order_form")
        order_form.resize(626, 571)
        self.order = QtWidgets.QPushButton(order_form)
        self.order.setGeometry(QtCore.QRect(400, 490, 201, 43))
        self.order.setStyleSheet("QPushButton{\n"
"  display: inline-block;\n"
"  padding: 10px 20px;\n"
"  font-size: 16px;\n"
"  text-align: center;\n"
"  text-decoration: none;\n"
"  background-color: #4CAF50;\n"
"  color: white;\n"
"  border: 2px solid #4CAF50;\n"
"  border-radius: 5px;\n"
"  transition: background-color 0.3s ease;\n"
"}\n"
"QPushButton:hover {\n"
"  background-color: #45a049;\n"
"  border-color: #45a049;\n"
"}\n"
"")
        self.order.setObjectName("order")
        self.label_11 = QtWidgets.QLabel(order_form)
        self.label_11.setGeometry(QtCore.QRect(20, 360, 81, 31))
        self.label_11.setStyleSheet("QLabel {\n"
"    font: 12pt \"MS Shell Dlg 2\";\n"
"    color: rgb(144, 158, 143) \n"
"}")
        self.label_11.setObjectName("label_11")
        self.date_end = QtWidgets.QLabel(order_form)
        self.date_end.setGeometry(QtCore.QRect(280, 260, 161, 31))
        self.date_end.setStyleSheet("QLabel {\n"
"    font: 12pt \"MS Shell Dlg 2\";\n"
"    color: rgb(144, 158, 143) \n"
"}")
        self.date_end.setObjectName("date_end")
        self.date_begining = QtWidgets.QLabel(order_form)
        self.date_begining.setGeometry(QtCore.QRect(280, 210, 171, 31))
        self.date_begining.setStyleSheet("QLabel {\n"
"    font: 12pt \"MS Shell Dlg 2\";\n"
"    color: rgb(144, 158, 143) \n"
"}")
        self.date_begining.setObjectName("date_begining")
        self.name_hotel = QtWidgets.QLabel(order_form)
        self.name_hotel.setGeometry(QtCore.QRect(280, 60, 151, 31))
        self.name_hotel.setStyleSheet("QLabel {\n"
"    font: 12pt \"MS Shell Dlg 2\";\n"
"    color: rgb(144, 158, 143) \n"
"}")
        self.name_hotel.setObjectName("name_hotel")
        self.name_client = QtWidgets.QLabel(order_form)
        self.name_client.setGeometry(QtCore.QRect(280, 110, 81, 31))
        self.name_client.setStyleSheet("QLabel {\n"
"    font: 12pt \"MS Shell Dlg 2\";\n"
"    color: rgb(144, 158, 143) \n"
"}")
        self.name_client.setObjectName("name_client")
        self.name_tour = QtWidgets.QLabel(order_form)
        self.name_tour.setGeometry(QtCore.QRect(280, 20, 141, 31))
        self.name_tour.setStyleSheet("QLabel {\n"
"    font: 12pt \"MS Shell Dlg 2\";\n"
"    color: rgb(144, 158, 143) \n"
"}")
        self.name_tour.setObjectName("name_tour")
        self.sum_tour = QtWidgets.QLabel(order_form)
        self.sum_tour.setGeometry(QtCore.QRect(140, 360, 361, 31))
        self.sum_tour.setStyleSheet("QLabel {\n"
"    font: 12pt \"MS Shell Dlg 2\";\n"
"    color: rgb(144, 158, 143) \n"
"}")
        self.sum_tour.setObjectName("sum_tour")
        self.verticalLayoutWidget = QtWidgets.QWidget(order_form)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(10, 10, 251, 281))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.label_13 = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.label_13.setStyleSheet("QLabel {\n"
"    font: 12pt \"MS Shell Dlg 2\";\n"
"    color: rgb(144, 158, 143) \n"
"}")
        self.label_13.setObjectName("label_13")
        self.verticalLayout.addWidget(self.label_13)
        self.label_10 = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.label_10.setStyleSheet("QLabel {\n"
"    font: 12pt \"MS Shell Dlg 2\";\n"
"    color: rgb(144, 158, 143) \n"
"}")
        self.label_10.setObjectName("label_10")
        self.verticalLayout.addWidget(self.label_10)
        self.label_9 = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.label_9.setStyleSheet("QLabel {\n"
"    font: 12pt \"MS Shell Dlg 2\";\n"
"    color: rgb(144, 158, 143) \n"
"}")
        self.label_9.setObjectName("label_9")
        self.verticalLayout.addWidget(self.label_9)
        self.label_14 = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.label_14.setStyleSheet("QLabel {\n"
"    font: 12pt \"MS Shell Dlg 2\";\n"
"    color: rgb(144, 158, 143) \n"
"}")
        self.label_14.setObjectName("label_14")
        self.verticalLayout.addWidget(self.label_14)
        self.label_12 = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.label_12.setStyleSheet("QLabel {\n"
"    font: 12pt \"MS Shell Dlg 2\";\n"
"    color: rgb(144, 158, 143) \n"
"}")
        self.label_12.setObjectName("label_12")
        self.verticalLayout.addWidget(self.label_12)
        self.label_15 = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.label_15.setStyleSheet("QLabel {\n"
"    font: 12pt \"MS Shell Dlg 2\";\n"
"    color: rgb(144, 158, 143) \n"
"}")
        self.label_15.setObjectName("label_15")
        self.verticalLayout.addWidget(self.label_15)
        self.label_7 = QtWidgets.QLabel(order_form)
        self.label_7.setGeometry(QtCore.QRect(440, 160, 51, 31))
        self.label_7.setStyleSheet("QLabel {\n"
"    font: 12pt \"MS Shell Dlg 2\";\n"
"    color: rgb(144, 158, 143) \n"
"}")
        self.label_7.setObjectName("label_7")
        self.people_adult = QtWidgets.QLineEdit(order_form)
        self.people_adult.setGeometry(QtCore.QRect(500, 160, 51, 31))
        self.people_adult.setStyleSheet("QLineEdit {\n"
"    border: 2px solid #98ff98;  /* Светло-зеленая рамка для QComboBox */\n"
"    border-radius: 5px;  /* Закругленные углы */\n"
"    padding: 5px;  /* Отступы вокруг текста */\n"
"    background-color: #e0ffe0;  /* Бледно-зеленый фон */\n"
"    color: #000000;  /* Черный цвет текста */\n"
"    selection-background-color: #90ee90;  /* Цвет фона для выделенного элемента */\n"
"}\n"
"QLineEdit  {\n"
"    font: 12pt \"MS Shell Dlg 2\";\n"
"    color: gray;\n"
"}\n"
"")
        self.people_adult.setObjectName("people_adult")
        self.label_6 = QtWidgets.QLabel(order_form)
        self.label_6.setGeometry(QtCore.QRect(270, 160, 91, 31))
        self.label_6.setStyleSheet("QLabel {\n"
"    font: 12pt \"MS Shell Dlg 2\";\n"
"    color: rgb(144, 158, 143) \n"
"}")
        self.label_6.setObjectName("label_6")
        self.people_child = QtWidgets.QLineEdit(order_form)
        self.people_child.setGeometry(QtCore.QRect(370, 160, 51, 31))
        self.people_child.setStyleSheet("QLineEdit {\n"
"    border: 2px solid #98ff98;  /* Светло-зеленая рамка для QComboBox */\n"
"    border-radius: 5px;  /* Закругленные углы */\n"
"    padding: 5px;  /* Отступы вокруг текста */\n"
"    background-color: #e0ffe0;  /* Бледно-зеленый фон */\n"
"    color: #000000;  /* Черный цвет текста */\n"
"    selection-background-color: #90ee90;  /* Цвет фона для выделенного элемента */\n"
"}\n"
"QLineEdit  {\n"
"    font: 12pt \"MS Shell Dlg 2\";\n"
"    color: gray;\n"
"}\n"
"")
        self.people_child.setObjectName("people_child")

        self.retranslateUi(order_form)
        QtCore.QMetaObject.connectSlotsByName(order_form)

    def retranslateUi(self, order_form):
        _translate = QtCore.QCoreApplication.translate
        order_form.setWindowTitle(_translate("order_form", "Frame"))
        self.order.setText(_translate("order_form", "Забронировать"))
        self.label_11.setText(_translate("order_form", "Сумма"))
        self.date_end.setText(_translate("order_form", "Дата конца тура"))
        self.date_begining.setText(_translate("order_form", "Дата начала тура"))
        self.name_hotel.setText(_translate("order_form", "Название отеля"))
        self.name_client.setText(_translate("order_form", "Клиент"))
        self.name_tour.setText(_translate("order_form", "Название тура"))
        self.sum_tour.setText(_translate("order_form", "Сумма"))
        self.label_13.setText(_translate("order_form", "Название тура"))
        self.label_10.setText(_translate("order_form", "Клиент"))
        self.label_9.setText(_translate("order_form", "Название отеля"))
        self.label_14.setText(_translate("order_form", "Дата начала тура"))
        self.label_12.setText(_translate("order_form", "Количество человек"))
        self.label_15.setText(_translate("order_form", "Дата конца тура"))
        self.label_7.setText(_translate("order_form", "Дети"))
        self.label_6.setText(_translate("order_form", "Взрослые"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    order_form = QtWidgets.QFrame()
    ui = Ui_order_form()
    ui.setupUi(order_form)
    order_form.show()
    sys.exit(app.exec_())
