# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'tours.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_tours_form(object):
    def setupUi(self, tours_form):
        tours_form.setObjectName("tours_form")
        tours_form.resize(625, 617)
        self.tableView = QtWidgets.QTableView(tours_form)
        self.tableView.setGeometry(QtCore.QRect(10, 260, 601, 341))
        self.tableView.setObjectName("tableView")
        self.country = QtWidgets.QLineEdit(tours_form)
        self.country.setGeometry(QtCore.QRect(80, 30, 221, 31))
        self.country.setStyleSheet("QLineEdit {\n"
"    border: 2px solid #98ff98;  /* Светло-зеленая рамка для QComboBox */\n"
"    border-radius: 5px;  /* Закругленные углы */\n"
"    padding: 5px;  /* Отступы вокруг текста */\n"
"    background-color: #e0ffe0;  /* Бледно-зеленый фон */\n"
"    color: #000000;  /* Черный цвет текста */\n"
"    selection-background-color: #90ee90;  /* Цвет фона для выделенного элемента */\n"
"}\n"
"QLineEdit  {\n"
"    font: 12pt \"MS Shell Dlg 2\";\n"
"    color: gray;\n"
"}\n"
"")
        self.country.setObjectName("country")
        self.label = QtWidgets.QLabel(tours_form)
        self.label.setGeometry(QtCore.QRect(10, 30, 71, 31))
        self.label.setStyleSheet("QLabel {\n"
"    font: 12pt \"MS Shell Dlg 2\";\n"
"    color: rgb(144, 158, 143) \n"
"}")
        self.label.setObjectName("label")
        self.hotel = QtWidgets.QLineEdit(tours_form)
        self.hotel.setGeometry(QtCore.QRect(380, 30, 221, 31))
        self.hotel.setStyleSheet("QLineEdit {\n"
"    border: 2px solid #98ff98;  /* Светло-зеленая рамка для QComboBox */\n"
"    border-radius: 5px;  /* Закругленные углы */\n"
"    padding: 5px;  /* Отступы вокруг текста */\n"
"    background-color: #e0ffe0;  /* Бледно-зеленый фон */\n"
"    color: #000000;  /* Черный цвет текста */\n"
"    selection-background-color: #90ee90;  /* Цвет фона для выделенного элемента */\n"
"}\n"
"QLineEdit  {\n"
"    font: 12pt \"MS Shell Dlg 2\";\n"
"    color: gray;\n"
"}\n"
"")
        self.hotel.setObjectName("hotel")
        self.label_2 = QtWidgets.QLabel(tours_form)
        self.label_2.setGeometry(QtCore.QRect(320, 30, 61, 31))
        self.label_2.setStyleSheet("QLabel {\n"
"    font: 12pt \"MS Shell Dlg 2\";\n"
"    color: rgb(144, 158, 143) \n"
"}")
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(tours_form)
        self.label_3.setGeometry(QtCore.QRect(310, 100, 131, 31))
        self.label_3.setStyleSheet("QLabel {\n"
"    font: 12pt \"MS Shell Dlg 2\";\n"
"    color: rgb(144, 158, 143) \n"
"}")
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(tours_form)
        self.label_4.setGeometry(QtCore.QRect(280, 140, 151, 31))
        self.label_4.setStyleSheet("QLabel {\n"
"    font: 12pt \"MS Shell Dlg 2\";\n"
"    color: rgb(144, 158, 143) \n"
"}")
        self.label_4.setObjectName("label_4")
        self.dateEdit = QtWidgets.QDateEdit(tours_form)
        self.dateEdit.setGeometry(QtCore.QRect(440, 100, 151, 31))
        self.dateEdit.setStyleSheet("QDateEdit  {\n"
"    border: 2px solid #98ff98;  /* Светло-зеленая рамка для QComboBox */\n"
"    border-radius: 5px;  /* Закругленные углы */\n"
"    padding: 5px;  /* Отступы вокруг текста */\n"
"    background-color: #e0ffe0;  /* Бледно-зеленый фон */\n"
"    color: #000000;  /* Черный цвет текста */\n"
"    selection-background-color: #90ee90;  /* Цвет фона для выделенного элемента */\n"
"}\n"
"QDateEdit {\n"
"    font: 12pt \"MS Shell Dlg 2\";\n"
"    color: gray;\n"
"}\n"
"")
        self.dateEdit.setWrapping(False)
        self.dateEdit.setButtonSymbols(QtWidgets.QAbstractSpinBox.UpDownArrows)
        self.dateEdit.setAccelerated(False)
        self.dateEdit.setProperty("showGroupSeparator", False)
        self.dateEdit.setCalendarPopup(True)
        self.dateEdit.setDate(QtCore.QDate(2024, 1, 7))
        self.dateEdit.setObjectName("dateEdit")
        self.dateEdit_2 = QtWidgets.QDateEdit(tours_form)
        self.dateEdit_2.setGeometry(QtCore.QRect(440, 140, 151, 31))
        self.dateEdit_2.setStyleSheet("QDateEdit  {\n"
"    border: 2px solid #98ff98;  /* Светло-зеленая рамка для QComboBox */\n"
"    border-radius: 5px;  /* Закругленные углы */\n"
"    padding: 5px;  /* Отступы вокруг текста */\n"
"    background-color: #e0ffe0;  /* Бледно-зеленый фон */\n"
"    color: #000000;  /* Черный цвет текста */\n"
"    selection-background-color: #90ee90;  /* Цвет фона для выделенного элемента */\n"
"}\n"
"QDateEdit {\n"
"    font: 12pt \"MS Shell Dlg 2\";\n"
"    color: gray;\n"
"}\n"
"")
        self.dateEdit_2.setCalendarPopup(True)
        self.dateEdit_2.setDate(QtCore.QDate(2024, 1, 31))
        self.dateEdit_2.setObjectName("dateEdit_2")
        self.label_5 = QtWidgets.QLabel(tours_form)
        self.label_5.setGeometry(QtCore.QRect(10, 90, 71, 31))
        self.label_5.setStyleSheet("QLabel {\n"
"    font: 12pt \"MS Shell Dlg 2\";\n"
"    color: rgb(144, 158, 143) \n"
"}")
        self.label_5.setObjectName("label_5")
        self.comboBox = QtWidgets.QComboBox(tours_form)
        self.comboBox.setGeometry(QtCore.QRect(100, 90, 71, 31))
        self.comboBox.setStyleSheet("QComboBox {\n"
"    border: 2px solid #98ff98;  /* Светло-зеленая рамка для QComboBox */\n"
"    border-radius: 5px;  /* Закругленные углы */\n"
"    padding: 5px;  /* Отступы вокруг текста */\n"
"    background-color: #e0ffe0;  /* Бледно-зеленый фон */\n"
"    color: #000000;  /* Черный цвет текста */\n"
"    selection-background-color: #90ee90;  /* Цвет фона для выделенного элемента */\n"
"}\n"
"QComboBox {\n"
"    font: 12pt \"MS Shell Dlg 2\";\n"
"    color: gray;\n"
"}\n"
"")
        self.comboBox.setObjectName("comboBox")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.label_9 = QtWidgets.QLabel(tours_form)
        self.label_9.setGeometry(QtCore.QRect(10, 140, 71, 31))
        self.label_9.setStyleSheet("QLabel {\n"
"    font: 12pt \"MS Shell Dlg 2\";\n"
"    color: rgb(144, 158, 143) \n"
"}")
        self.label_9.setObjectName("label_9")
        self.price = QtWidgets.QLineEdit(tours_form)
        self.price.setGeometry(QtCore.QRect(80, 140, 151, 31))
        self.price.setStyleSheet("QLineEdit {\n"
"    border: 2px solid #98ff98;  /* Светло-зеленая рамка для QComboBox */\n"
"    border-radius: 5px;  /* Закругленные углы */\n"
"    padding: 5px;  /* Отступы вокруг текста */\n"
"    background-color: #e0ffe0;  /* Бледно-зеленый фон */\n"
"    color: #000000;  /* Черный цвет текста */\n"
"    selection-background-color: #90ee90;  /* Цвет фона для выделенного элемента */\n"
"}\n"
"QLineEdit  {\n"
"    font: 12pt \"MS Shell Dlg 2\";\n"
"    color: gray;\n"
"}\n"
"")
        self.price.setText("")
        self.price.setObjectName("price")
        self.filter = QtWidgets.QPushButton(tours_form)
        self.filter.setGeometry(QtCore.QRect(30, 200, 201, 41))
        self.filter.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.filter.setStyleSheet("QPushButton{\n"
"  display: inline-block;\n"
"  padding: 10px 20px;\n"
"  font-size: 16px;\n"
"  text-align: center;\n"
"  text-decoration: none;\n"
"  background-color: #4CAF50;\n"
"  color: white;\n"
"  border: 2px solid #4CAF50;\n"
"  border-radius: 5px;\n"
"  transition: background-color 0.3s ease;\n"
"}\n"
"QPushButton:hover {\n"
"  background-color: #45a049;\n"
"  border-color: #45a049;\n"
"}\n"
"")
        self.filter.setObjectName("filter")

        self.retranslateUi(tours_form)
        QtCore.QMetaObject.connectSlotsByName(tours_form)

    def retranslateUi(self, tours_form):
        _translate = QtCore.QCoreApplication.translate
        tours_form.setWindowTitle(_translate("tours_form", "Frame"))
        self.label.setText(_translate("tours_form", "Страна"))
        self.label_2.setText(_translate("tours_form", "Отель"))
        self.label_3.setText(_translate("tours_form", "Дата Начала"))
        self.label_4.setText(_translate("tours_form", "Дата окончания"))
        self.label_5.setText(_translate("tours_form", "Рейтинг"))
        self.comboBox.setItemText(0, _translate("tours_form", "5"))
        self.comboBox.setItemText(1, _translate("tours_form", "4.5"))
        self.comboBox.setItemText(2, _translate("tours_form", "4"))
        self.comboBox.setItemText(3, _translate("tours_form", "3.5"))
        self.comboBox.setItemText(4, _translate("tours_form", "3"))
        self.comboBox.setItemText(5, _translate("tours_form", "2.5"))
        self.comboBox.setItemText(6, _translate("tours_form", "2"))
        self.comboBox.setItemText(7, _translate("tours_form", "1.5"))
        self.comboBox.setItemText(8, _translate("tours_form", "1"))
        self.comboBox.setItemText(9, _translate("tours_form", "0.5"))
        self.label_9.setText(_translate("tours_form", "Цена"))
        self.filter.setText(_translate("tours_form", "Применить фильтры"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    tours_form = QtWidgets.QFrame()
    ui = Ui_tours_form()
    ui.setupUi(tours_form)
    tours_form.show()
    sys.exit(app.exec_())
