# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'yes.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_yes(object):
    def setupUi(self, yes):
        yes.setObjectName("yes")
        yes.resize(320, 214)
        self.label = QtWidgets.QLabel(yes)
        self.label.setGeometry(QtCore.QRect(90, 70, 151, 61))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label.setFont(font)
        self.label.setWordWrap(True)
        self.label.setObjectName("label")

        self.retranslateUi(yes)
        QtCore.QMetaObject.connectSlotsByName(yes)

    def retranslateUi(self, yes):
        _translate = QtCore.QCoreApplication.translate
        yes.setWindowTitle(_translate("yes", "Frame"))
        self.label.setText(_translate("yes", "Авторизация прошла успешно!"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    yes = QtWidgets.QFrame()
    ui = Ui_yes()
    ui.setupUi(yes)
    yes.show()
    sys.exit(app.exec_())
